name: Database Backup & Restore

on:
  schedule:
    - cron: '0 */24 * * *'  # Runs every 24 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  backup_restore:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Executable Permissions (Linux Only)
        if: runner.os != 'Windows'
        run: chmod +x backups/backup_db.sh backups/restore_db.sh
        shell: bash

      - name: Debug MySQL Connection
        shell: pwsh
        env:
          MYSQL_HOST: "192.168.29.245"
          MYSQL_PORT: "3306"
        run: |
          Write-Output "🔍 Checking MySQL connection..."
          $result = Test-NetConnection -ComputerName $env:MYSQL_HOST -Port $env:MYSQL_PORT
          if (-not $result.TcpTestSucceeded) {
            Write-Output "❌ Port unreachable!"
            exit 1
          }
          Write-Output "✅ MySQL port is reachable."

      - name: Check MySQL Status
        shell: bash
        env:
          MYSQL_HOST: "192.168.29.245"
          MYSQL_PORT: "3306"
          MYSQL_USER: "ci_user"
          MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"
        run: |
          echo "🔍 Checking MySQL status..."
          if ! mysqladmin ping -h "$MYSQL_HOST" -P "$MYSQL_PORT" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --silent; then
            echo "❌ MySQL is not accessible!"
            exit 1
          fi
          echo "✅ MySQL is accessible."

      - name: Run Backup Script
        shell: bash
        env:
          MYSQL_USER: "ci_user"
          MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"
          MYSQL_HOST: "192.168.29.245"
          MYSQL_PORT: "3306"
          MYSQL_DB: "php_ecom"
        run: bash backups/backup_db.sh

      - name: Mark repo as safe
        shell: bash
        run: git config --global --add safe.directory "C:/Users/navna/actions-runner/1st/php_project1/php_project1"

      - name: Commit and Push Backup
        shell: bash
        env:
          GH_PAT: "${{ secrets.GH_PAT }}"
        run: |
          echo "🔄 Committing backup files..."
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add backups/
          if git diff --cached --quiet; then
            echo "⚠️ No changes to commit."
            exit 0
          fi
          git commit -m "🔄 Database backup: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/yash2364/php_project1.git

      - name: Run Restore Script (Manual Trigger Only)
        if: github.event_name == 'workflow_dispatch'
        shell: bash
        env:
          MYSQL_USER: "ci_user"
          MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"
          MYSQL_HOST: "192.168.29.245"
          MYSQL_PORT: "3306"
          MYSQL_DB: "php_ecom"
        run: bash backups/restore_db.sh
