name: Database Backup

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set executable permission
        run: chmod +x backups/backup_db.sh  # 🔹 Fix: Use correct path

      - name: Set up MySQL
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          sudo systemctl start mysql
          mysql -u pma -p$MYSQL_PASSWORD -e "CREATE DATABASE IF NOT EXISTS your_database;"
          mysql -u pma -p$MYSQL_PASSWORD -e "CREATE USER 'pma'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
          mysql -u pma -p$MYSQL_PASSWORD -e "GRANT ALL PRIVILEGES ON *.* TO 'pma'@'%' WITH GRANT OPTION;"
          mysql -u pma -p$MYSQL_PASSWORD -e "FLUSH PRIVILEGES;"

      - name: Run Backup Script
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: bash backups/backup_db.sh  # 🔹 Fix: Use correct path

      - name: Commit and Push Backup
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add backups/
          git commit -m "🔄 Database backup: $(date)"
          git push
