name: Database Backup

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Executable Permission
        run: chmod +x backups/backup_db.sh backups/restore_db.sh

      - name: Run Backup Script
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: bash backups/backup_db.sh

      - name: Commit and Push Backup
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add backups/
          git commit -m "🔄 Database backup: $(date)"
          git push
