name: Database Backup & Restore

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  backup_restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Executable Permissions
        run: chmod +x backups/backup_db.sh backups/restore_db.sh

      - name: Check MySQL Status
        run: mysqladmin ping -h 127.0.0.1 -u root --password="${{ secrets.MYSQL_PASSWORD }}" || exit 1

      - name: Run Backup Script
        env:
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DB: "php_ecom"
        run: bash backups/backup_db.sh

      - name: Commit and Push Backup
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add backups/
          git commit -m "🔄 Database backup: $(date)"
          git push

      - name: Run Restore Script (Optional)
        if: github.event_name == 'workflow_dispatch'
        env:
          MYSQL_USER: "root"
          MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"
          MYSQL_HOST: "127.0.0.1"
          MYSQL_DB: "php_ecom"
        run: bash backups/restore_db.sh
