name: Track SQL Server Database Changes 

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Manual trigger for testing

jobs:
  export-database:
    runs-on: ubuntu-22.04  # ✅ Use Ubuntu 22.04 instead of ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Microsoft SQL Server Repository
        run: |
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /usr/share/keyrings/microsoft-prod.key > /dev/null
          echo "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-prod.key] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update

      - name: Install SQL Server Client Tools
        run: sudo apt-get install -y mssql-tools unixodbc-dev

      - name: Export Database Schema (php_ecom)
        run: |
          sqlcmd -S ${{ secrets.DB_HOST }},${{ secrets.DB_PORT }} \
                 -U ${{ secrets.DB_USER }} \
                 -P ${{ secrets.DB_PASS }} \
                 -d php_ecom \
                 -Q "EXEC sp_help" > database/schema.sql

      - name: Export Database Data (php_ecom)
        run: |
          sqlcmd -S ${{ secrets.DB_HOST }},${{ secrets.DB_PORT }} \
                 -U ${{ secrets.DB_USER }} \
                 -P ${{ secrets.DB_PASS }} \
                 -d php_ecom \
                 -Q "SET NOCOUNT ON; EXEC sp_MSforeachtable 'SELECT * FROM ?'" > database/data.sql

      - name: Check for Changes and Commit
        run: |
          git add database/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated php_ecom database schema & data" && git push)
